=== mmcintyre1/book-summaries/book_summary_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "The root schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "required": [
    "title",
    "authors",
    "isbn",
    "reason_for_reading",
    "publication_date",
    "original_language",
    "genre",
    "start_date",
    "finish_date",
    "pages",
    "word_count",
    "flesh_kincaid_reading_level",
    "synopsis",
    "key_takeaway",
    "key_ideas",
    "counter_ideas",
    "quotes",
    "vocabulary",
    "review",
    "review_score",
    "other_reading"
  ],
  "properties": {
    "title": {
      "$id": "#/properties/title",
      "type": "object",
      "title": "The title schema",
      "description": "An explanation about the purpose of this instance.",
      "default": {},
      "required": [
        "main_title",
        "subtitle"
      ],
      "properties": {
        "main_title": {
          "$id": "#/properties/title/properties/main_title",
          "type": "string",
          "title": "The main_title schema",
          "description": "An explanation about the purpose of this instance.",
          "default": ""
        },
        "subtitle": {
          "$id": "#/properties/title/properties/subtitle",
          "type": "null",
          "title": "The subtitle schema",
          "description": "An explanation about the purpose of this instance.",
          "default": null
        }
      },
      "additionalProperties": false
    },
    "authors": {
      "$id": "#/properties/authors",
      "type": "array",
      "title": "The authors schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/authors/items",
        "type": "object",
        "title": "The items schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "required": [
          "first_name",
          "last_name",
          "description"
        ],
        "properties": {
          "first_name": {
            "$id": "#/properties/authors/items/properties/first_name",
            "type": "string",
            "title": "The first_name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "last_name": {
            "$id": "#/properties/authors/items/properties/last_name",
            "type": "string",
            "title": "The last_name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "description": {
            "$id": "#/properties/authors/items/properties/description",
            "type": "null",
            "title": "The description schema",
            "description": "An explanation about the purpose of this instance.",
            "default": null
          }
        },
        "additionalProperties": false
      }
    },
    "isbn": {
      "$id": "#/properties/isbn",
      "type": "string",
      "title": "The isbn schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "reason_for_reading": {
      "$id": "#/properties/reason_for_reading",
      "type": "string",
      "title": "The reason_for_reading schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "publication_date": {
      "$id": "#/properties/publication_date",
      "type": "string",
      "title": "The publication_date schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "original_language": {
      "$id": "#/properties/original_language",
      "type": "string",
      "title": "The original_language schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "genre": {
      "$id": "#/properties/genre",
      "type": "string",
      "title": "The genre schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "start_date": {
      "$id": "#/properties/start_date",
      "type": "string",
      "title": "The start_date schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "finish_date": {
      "$id": "#/properties/finish_date",
      "type": "string",
      "title": "The finish_date schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "pages": {
      "$id": "#/properties/pages",
      "type": "integer",
      "title": "The pages schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0
    },
    "word_count": {
      "$id": "#/properties/word_count",
      "type": "integer",
      "title": "The word_count schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0
    },
    "flesh_kincaid_reading_level": {
      "$id": "#/properties/flesh_kincaid_reading_level",
      "type": "number",
      "title": "The flesh_kincaid_reading_level schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0.0
    },
    "synopsis": {
      "$id": "#/properties/synopsis",
      "type": "string",
      "title": "The synopsis schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "key_takeaway": {
      "$id": "#/properties/key_takeaway",
      "type": "string",
      "title": "The key_takeaway schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "key_ideas": {
      "$id": "#/properties/key_ideas",
      "type": "array",
      "title": "The key_ideas schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/key_ideas/items",
        "type": "object",
        "title": "The items schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "required": [
          "topic_heading",
          "text"
        ],
        "properties": {
          "topic_heading": {
            "$id": "#/properties/key_ideas/items/properties/topic_heading",
            "type": "string",
            "title": "The topic_heading schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "text": {
            "$id": "#/properties/key_ideas/items/properties/text",
            "type": "string",
            "title": "The text schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          }
        },
        "additionalProperties": false
      }
    },
    "counter_ideas": {
      "$id": "#/properties/counter_ideas",
      "type": "array",
      "title": "The counter_ideas schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/counter_ideas/items",
        "type": "object",
        "title": "The items schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "required": [
          "topic heading",
          "text"
        ],
        "properties": {
          "topic heading": {
            "$id": "#/properties/counter_ideas/items/properties/topic%20heading",
            "type": "string",
            "title": "The topic heading schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "text": {
            "$id": "#/properties/counter_ideas/items/properties/text",
            "type": "string",
            "title": "The text schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          }
        },
        "additionalProperties": false
      }
    },
    "quotes": {
      "$id": "#/properties/quotes",
      "type": "array",
      "title": "The quotes schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/quotes/items",
        "type": "object",
        "title": "The items schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "required": [
          "quote",
          "page"
        ],
        "properties": {
          "quote": {
            "$id": "#/properties/quotes/items/properties/quote",
            "type": "string",
            "title": "The quote schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "page": {
            "$id": "#/properties/quotes/items/properties/page",
            "type": "string",
            "title": "The page schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          }
        },
        "additionalProperties": false
      }
    },
    "vocabulary": {
      "$id": "#/properties/vocabulary",
      "type": "array",
      "title": "The vocabulary schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/vocabulary/items",
        "type": "object",
        "title": "The items schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "required": [
          "word",
          "part_of_speech",
          "pronunciation",
          "definition"
        ],
        "properties": {
          "word": {
            "$id": "#/properties/vocabulary/items/properties/word",
            "type": "string",
            "title": "The word schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "part_of_speech": {
            "$id": "#/properties/vocabulary/items/properties/part_of_speech",
            "type": "string",
            "title": "The part_of_speech schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "pronunciation": {
            "$id": "#/properties/vocabulary/items/properties/pronunciation",
            "type": "string",
            "title": "The pronunciation schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "definition": {
            "$id": "#/properties/vocabulary/items/properties/definition",
            "type": "string",
            "title": "The definition schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          }
        },
        "additionalProperties": false
      }
    },
    "review": {
      "$id": "#/properties/review",
      "type": "string",
      "title": "The review schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "review_score": {
      "$id": "#/properties/review_score",
      "type": "number",
      "title": "The review_score schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0.0
    },
    "other_reading": {
      "$id": "#/properties/other_reading",
      "type": "array",
      "title": "The other_reading schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/other_reading/items",
        "type": "object",
        "title": "The items schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "required": [
          "book_title",
          "author"
        ],
        "properties": {
          "book_title": {
            "$id": "#/properties/other_reading/items/properties/book_title",
            "type": "string",
            "title": "The book_title schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          },
          "author": {
            "$id": "#/properties/other_reading/items/properties/author",
            "type": "string",
            "title": "The author schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== mmcintyre1/book-summaries/2021/01/together.json
{
  "title": {
    "main_title": "Together",
    "subtitle": "The Healing Power of Human Connection in a Sometimes Lonely World"
  },
  "authors": [
    {
      "first_name": "Vivek",
      "last_name": "Murthy",
      "description": "The 19th Surgeon General of the US under Barack Obama"
    }
  ],
  "isbn": "",
  "reason_for_reading": "Pleasure",
  "publication_date": "",
  "original_language": "ENG",
  "genre": "non-fiction;",
  "start_date": "01-24-2021",
  "finish_date": "01-30-2021",
  "pages": 372,
  "word_count": 116746,
  "flesh_kincaid_reading_level": 78.89,
  "synopsis": "",
  "key_takeaway": "",
  "key_ideas": [
    {
      "topic_heading": "",
      "text": ""
    }
  ],
  "counter_ideas": [
    {
      "topic heading": "",
      "text": ""
    }
  ],
  "quotes": [
    {
      "quote": "",
      "page": ""
    }
  ],
  "vocabulary": [
    {
      "word": "",
      "part_of_speech": "",
      "pronunciation": "",
      "definition": ""
    }
  ],
  "review": "",
  "review_score": 3.0,
  "other_reading": [
    {
      "book_title": "",
      "author": ""
    }
  ]
}

=== mmcintyre1/book-summaries/2021/02/the_tao_of_pooh_and_the_te_of_piglet.json
{
  "title": {
    "main_title": "The Tao of Pooh and the Te of Piglet",
    "subtitle": "The principles of Taoism demonstrated by Winnie the Pooh and Piglet"
  },
  "authors": [
    {
      "first_name": "Benjamin",
      "last_name": "Hoff",
      "description": null
    }
  ],
  "isbn": "978-1405293778",
  "reason_for_reading": "pleasure",
  "publication_date": "2019-09-05",
  "original_language": "ENG",
  "genre": "non-fiction;self-help;taoism;philosophy",
  "start_date": "2021-02-04",
  "finish_date": "2021-02-07",
  "pages": 424,
  "word_count": 65000,
  "flesh_kincaid_reading_level": 70,
  "synopsis": "",
  "key_takeaway": "",
  "key_ideas": [],
  "counter_ideas": [],
  "quotes": [],
  "vocabulary": [],
  "review": "",
  "review_score": 2,
  "other_reading": [
    {
      "book_title": "",
      "author": ""
    }
  ]
}

=== mmcintyre1/book-summaries/2021/01/a_song_for_a_new_day.json
{
  "title": {
    "main_title": "A Song For a New Day",
    "subtitle": null
  },
  "authors": [
    {
      "first_name": "Sarah",
      "last_name": "Pinsker",
      "description": ""
    }
  ],
  "isbn": "9781984802583",
  "reason_for_reading": "Pleasure",
  "publication_date": "09-10-2019",
  "original_language": "ENG",
  "genre": "fiction;science-fiction;speculative fiction",
  "start_date": "01-20-2021",
  "finish_date": "01-24-2021",
  "pages": 372,
  "word_count": 116746,
  "flesh_kincaid_reading_level": 78.89,
  "synopsis": "In the Before, when the government didn't prohibit large public gatherings, Luce Cannon was on top of the world. One of her songs had just taken off and she was on her way to becoming a star. Now, in the After, terror attacks and deadly viruses have led the government to ban concerts, and Luce's connection to the world--her music, her purpose\u2014is closed off forever. She does what she has to do: she performs in illegal concerts to a small but passionate community, always evading the law.\r\n\r\nRosemary Laws barely remembers the Before times. She spends her days in Hoodspace, helping customers order all of their goods online for drone delivery\u2014no physical contact with humans needed. By lucky chance, she finds a new job and a new calling: discover amazing musicians and bring their concerts to everyone via virtual reality. The only catch is that she'll have to do something she's never done before and go out in public. Find the illegal concerts and bring musicians into the limelight they deserve. But when she sees how the world could actually be, that won\u2019t be enough.",
  "key_takeaway": "",
  "key_ideas": [
    {
      "topic_heading": "",
      "text": ""
    }
  ],
  "counter_ideas": [
    {
      "topic heading": "",
      "text": ""
    }
  ],
  "quotes": [
    {
      "quote": "",
      "page": ""
    }
  ],
  "vocabulary": [
    {
      "word": "",
      "part_of_speech": "",
      "pronunciation": "",
      "definition": ""
    }
  ],
  "review": "",
  "review_score": 3.0,
  "other_reading": [
    {
      "book_title": "",
      "author": ""
    }
  ]
}
